import { useEffect, useState } from 'react';
import { Card, Button, Badge } from '../../../components';
import { Award, CheckCircle, AlertTriangle, Eye, RefreshCw, Sparkles, Building2, MapPin } from 'lucide-react';
import { useCareerAgentStore } from '../../../store/careerAgent';
import { useResumeStore } from '../../../store';
import MatchingScoreBar from '../shared/MatchingScoreBar';
import JobDescriptionFormatter from '../shared/JobDescriptionFormatter';

export default function JobMatchesDashboard() {
  const [selectedMatch, setSelectedMatch] = useState(null);
  const [formatJobId, setFormatJobId] = useState(null);
  const token = useResumeStore((state) => state.token);
  
  const {
    jobMatches,
    matchesLoading,
    matchesError,
    matchJobs,
  } = useCareerAgentStore();

  useEffect(() => {
    if (token && jobMatches.length === 0) {
      matchJobs(token);
    }
  }, [token]);

  const handleEvaluate = async () => {
    await matchJobs(token);
  };

  const handleApply = (match) => {
    if (match.applyUrl) {
      const absoluteUrl = match.applyUrl.startsWith('http') ? match.applyUrl : `https://${match.applyUrl}`;
      window.open(absoluteUrl, '_blank', 'noopener,noreferrer');
    } else {
      alert('Application link is not available.');
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold text-slate-900">Intelligent Job Matches</h2>
          <p className="text-slate-600 mt-1">
            Real-time suitability scoring generated by AI matching agents.
          </p>
        </div>
        <Button
          onClick={handleEvaluate}
          disabled={matchesLoading}
          className="flex items-center gap-2 bg-gradient-brand text-white shadow-soft-sm font-semibold"
        >
          <RefreshCw className={`h-4 w-4 ${matchesLoading ? 'animate-spin' : ''}`} />
          {matchesLoading ? 'Evaluating...' : 'Re-Evaluate Matches'}
        </Button>
      </div>

      {matchesError && (
        <Card className="p-4 border-red-200 bg-red-50 text-red-800">
          Error calculating matches: {matchesError}
        </Card>
      )}

      {/* Main Layout Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Matches Feed */}
        <div className="lg:col-span-2 space-y-4">
          {jobMatches.length === 0 ? (
            <Card className="p-12 text-center border-dashed">
              <Award className="h-12 w-12 text-indigo-300 mx-auto mb-4" />
              <h3 className="text-lg font-bold text-slate-800 font-sans">No Matches Evaluated</h3>
              <p className="text-slate-500 mt-2 max-w-sm mx-auto">
                No matching scores calculated yet. Trigger job discovery first, then run match evaluation.
              </p>
              <Button onClick={handleEvaluate} className="mt-4" variant="primary">
                Evaluate Job Matches
              </Button>
            </Card>
          ) : (
            <div className="space-y-3">
              {jobMatches.map((match) => (
                <Card
                  key={match.id || match.jobId}
                  onClick={() => setSelectedMatch(match)}
                  className={`p-4 flex items-center justify-between gap-4 cursor-pointer hover:shadow-soft-md transition-all border-l-4 ${
                    selectedMatch?.id === match.id
                      ? 'border-indigo-600 bg-indigo-50/20 shadow-soft-sm'
                      : 'border-l-slate-200 hover:border-l-indigo-400'
                  }`}
                >
                  <div className="flex-1 space-y-1">
                    <div className="flex items-center gap-2">
                      <h4 className="font-bold text-slate-900 text-base">{match.title}</h4>
                      <Badge variant={match.matchScore >= 85 ? 'success' : match.matchScore >= 70 ? 'primary' : 'warning'}>
                        {Math.round(match.matchScore)}% Match
                      </Badge>
                    </div>
                    <p className="text-sm font-semibold text-slate-600 flex items-center gap-1">
                      <Building2 size={14} className="text-slate-400" />
                      {match.company}
                    </p>
                    <p className="text-xs text-slate-500 flex items-center gap-1">
                      <MapPin size={13} className="text-slate-400" />
                      {match.location}
                    </p>
                  </div>

                  <div className="flex items-center gap-3">
                    <MatchingScoreBar score={match.matchScore} size="sm" showPercentage={false} />
                    <Button variant="ghost" size="sm" className="p-2">
                      <Eye size={18} className="text-indigo-600" />
                    </Button>
                  </div>
                </Card>
              ))}
            </div>
          )}
        </div>

        {/* Explainability Side Panel */}
        <div className="lg:col-span-1">
          {selectedMatch ? (
            <Card className="p-6 sticky top-6 space-y-6 shadow-soft-lg">
              <div className="space-y-3 text-center border-b border-slate-100 pb-5">
                <h3 className="text-xl font-bold text-slate-900">{selectedMatch.title}</h3>
                <p className="text-slate-600 font-semibold">{selectedMatch.company}</p>
                <div className="flex justify-center items-center gap-3 mt-2">
                  <MatchingScoreBar score={selectedMatch.matchScore} size="lg" showPercentage />
                  <span className="text-lg font-extrabold text-slate-800">Match Score</span>
                </div>
                <Button
                  onClick={() => setFormatJobId(selectedMatch.jobId)}
                  className="w-full bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 text-white font-semibold flex items-center justify-center gap-1.5 mt-3"
                >
                  <Sparkles size={16} /> View Recruiter Format (ATS)
                </Button>
              </div>

              {/* Relevance Summary */}
              {selectedMatch.explanation?.relevanceSummary && (
                <div className="space-y-2">
                  <h4 className="font-bold text-slate-800 flex items-center gap-2 text-sm">
                    <Sparkles size={16} className="text-indigo-600 animate-pulse" />
                    AI Relevance Summary
                  </h4>
                  <p className="text-sm text-slate-600 leading-relaxed bg-slate-50 p-3 rounded-xl border border-slate-100">
                    {selectedMatch.explanation.relevanceSummary}
                  </p>
                </div>
              )}

              {/* Skills breakdown */}
              <div className="space-y-4">
                {/* Matching Skills */}
                <div className="space-y-2">
                  <h4 className="font-bold text-green-700 flex items-center gap-2 text-sm">
                    <CheckCircle size={16} />
                    Matching Skills ({selectedMatch.explanation?.matchingSkills?.length || 0})
                  </h4>
                  <div className="flex flex-wrap gap-1.5">
                    {selectedMatch.explanation?.matchingSkills?.map((skill) => (
                      <Badge key={skill} variant="success" size="sm">
                        ✓ {skill}
                      </Badge>
                    ))}
                    {!selectedMatch.explanation?.matchingSkills?.length && (
                      <span className="text-xs text-slate-400">None identified</span>
                    )}
                  </div>
                </div>

                {/* Missing Skills */}
                <div className="space-y-2">
                  <h4 className="font-bold text-amber-700 flex items-center gap-2 text-sm">
                    <AlertTriangle size={16} />
                    Missing / Skill Gaps ({selectedMatch.explanation?.missingSkills?.length || 0})
                  </h4>
                  <div className="flex flex-wrap gap-1.5">
                    {selectedMatch.explanation?.missingSkills?.map((skill) => (
                      <Badge key={skill} variant="warning" size="sm">
                        ⚠️ {skill}
                      </Badge>
                    ))}
                    {!selectedMatch.explanation?.missingSkills?.length && (
                      <span className="text-xs text-slate-400">Perfect match! No missing skills.</span>
                    )}
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex gap-3 pt-4 border-t border-slate-100">
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={() => setSelectedMatch(null)}
                >
                  Close
                </Button>
                <Button
                  variant="primary"
                  className="flex-1 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold"
                  onClick={() => handleApply(selectedMatch)}
                >
                  Apply Externally
                </Button>
              </div>
            </Card>
          ) : (
            <Card className="p-6 text-center border-dashed py-16">
              <Award className="h-12 w-12 text-slate-300 mx-auto mb-3" />
              <p className="text-slate-500 text-sm">
                Select a match from the feed to view the deep skill gap analysis and relevance report.
              </p>
            </Card>
          )}
        </div>
      </div>
      {formatJobId && (
        <JobDescriptionFormatter jobId={formatJobId} onClose={() => setFormatJobId(null)} />
      )}
    </div>
  );
}
